### PR TITLE
Views Update

### LINKED ISSUE #47: [Bug] Login button only works when window is in original position.
Noticing that after I move the pop-up window when running the program the login button is no longer clickable.

### PR DESCRIPTION
**Pull request by jordanjanakievski**
Overall clean up of the codebase

### Additions
- JavaDoc on the public methods missing it
- Implementation of CLEAN for the game over prompt
- Removal of game related print statements

@declanlim can comment on his additions

This will be merged last

### CODE REVIEW

**Comment by declanlim** [comment]
Added some more code to clean up the codebase:

- Renamed the tests in the PiecesTest file
- JavaDoc on the public methods in the pieces child classes
- Updated the README file with screenshots

**Comment by declanlim** [comment]
Pieces tests for the King, Queen, Rook, Bishop and Knight still appear to be failing the automatic checks from Github classroom. However, I am unable to find any bugs on my own device and can successfully run all the tests in the PiecesTests.java file. The tests have also been run on other people's devices and they also have no issue with the tests.

**Review by HiAidenG — APPROVED** [review]
Good fix on #47, also not sure why the autograding is failing, everything works for me locally... 
I also like the addition of images to our README, I think it gives our users a better idea of what to expect from our program. 

Documentation looking very professional!

**Review by cxwang1037738928 — APPROVED** [review]
Good addition to the README

**Comment by usman-khan888** [comment]
Fixes #47

**Pull request merged**
